# Generated by Django 2.2.7 on 2019-11-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='links',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
