# Generated by Django 2.2.7 on 2019-11-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20191114_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
